### ISSUE TITLE
Add ability to safely call functions

### ISSUE THREAD

**Issue by derekparker** [go-delve/delve#119]
Add support for calling functions within the current scope. Should allow specifying in-scope variables as arguments to these function calls.

`call myFunc(localVar, 4, "foo")`

**Comment by aarzilli** [comment]
Comment moved here from PR #331:

I did think a bit about calling functions (without writing any code so this is purely philosophical) this is what I thought would be the pain points:

a. panics
b. breakpoints getting hit while evaluating a function
c. our goroutine getting scheduled out -- which makes (b) worse.

Regarding (a), one solution is to set a breakpoint on panic and abort the evaluation as soon as it is called, before it starts unwinding the stack. This is not ideal, the panic could be recovered by a frame below our dummy frame, but given how panics are generally used by go code it should be a big deal.

The other possibility would be to abort the call only when the stack unwind gets to our dummy frame, possibly modifying the `g` struct to slip in our own fake `_defer` object?

Regarding (b) and (c) I have two possible solution

### Orthodox solution

For (b) we disable all user breakpoints. (c) is hard: I'm not sure it's possible to suppress co-operative scheduler calls, maybe abort on them? Even pre-emptive scheduler calls may be hard because they seem to be at least in part intertwined with stack resizes (which we can not suppress).

### Unorthodox solution

We call `Continue` in the middle of `Call`, any breakpoint that gets hit is reported to the user normally, the rest of `Call` is executed when its temp breakpoint (which would have a condition on the goroutine id) gets hit, in a callback executed by `Continue`.

This is easier to implement because we don't have to worry about (b) and especially (c) but it's weird for the user. 

```
> main.somefunction() somefile.go:10
(dlv) print a
3
(dlv) print double(a)
Command failed: function calls are not supported
```

The user must use a different command to enable function calls, this command will have a behaviour similar to `continue` and use a similar API, let's call this command `exec`:

```
(dlv) exec double(a)
> main.someotherfunction() somefile.go:50
```

the function call did not complete, the user got a breakpoint somewhere else in the program, the user can interact with the debugger:

```
(dlv) continue
> main.somefunction() somefile.go:10
    double(a) = 6
(dlv)
``` 

after another continue the original `exec` call completes and the user gets the evaluation result: `double(a) = 6`.

**Comment by ignatov** [comment]
@derekparker @aarzilli Do we need some changes in Go itself for this issue?

**Comment by aarzilli** [comment]
@ignatov: likely yes. On top of the design problems in my previous message there is also another thing to be considered. Let's say we want to initiate a call, from the debugger, to a function F from goroutine G. 
We shall call the activation frame currently on top of the stack for G the "dangerframe"

1. We can't overwrite memory in the dangerframe because the garbage collector could run while F is executing and collect live object because we overwrote the dangerframe, so we need to add memory do G's stack (because goroutines stack are tight): how?

2. Let's say there was enough space on G's stack to push our arguments, space for the return value and some fake return address. Now we change RIP and restart the process to execute F. If the garbage collector runs and tries to unwind G's stack it will get hopelessly confused once it gets to the dangerframe because we made dangerframe extra fat by adding one extra arguments area at the end of it.

3. Even if this doesn't happen the dangerframe is not stopped at a safe point so the garbage collector wouldn't have a good pointer bitmap to determine which pointers on the dangerframe are live.

**Comment by ignatov** [comment]
@aarzilli maybe we should file an issue in https://github.com/golang/go/issues? We had a conversation with @rsc, and he told us that Go team is going to provide a good basement for debugger at least.

**Comment by komuW** [comment]
@ignatov Did you create an issue at https://github.com/golang/go/issues ?
I'm new to Go and was trying to run a func in a delve session and I came across this issue.

I'm asking, since I would like to file an issue in the Go repo if you haven't. Especially now that Go is collecting feedback on stuff that should go into Go2, I think a better debugging experience should be of utmost importance and having an issue open with them would greatly help.
cc @derekparker @aarzilli

**Comment by ignatov** [comment]
@komuW 
>  Did you create an issue at https://github.com/golang/go/issues ?
No, I didn't. Could you please do it?

**Comment by phemmer** [comment]
Pardon my jumping in here, but could we side-step all the GC related issues by disabling it during the function call?
I can think of 2 risks to doing this.
1. function call goes nuts and consumes all memory. I think the risk here is pretty minimal, and acceptable if it gets us function calls.
2. function call explicitly triggers a GC. I'm not sure how the delve interacts with the Go runtime, but it seems like we might be able to set a breakpoint on `runtime.GC()` so that we can clean up the stack, or make it a noop.

**Comment by jkryanchou** [comment]
Is it supported now?

**Comment by komuw** [comment]
update: 
I had opened an issue on the Go issue tracker and it got a lot of traction: https://github.com/golang/go/issues/21678

Additionally, there is a new proposal; https://github.com/golang/go/issues/24543 that if adopted would `have side benefits for debugger function calls`

**Comment by mikeschinkel** [comment]
GoLand from JetBrains is blocking a feature because of this issue:

https://youtrack.jetbrains.com/issue/GO-3433

Just an FYI

**Comment by coriolinus** [comment]
Given that https://go-review.googlesource.com/c/go/+/109699/ is merged into go 1.13, which has been released, does there now exist a reasonable estimate when this feature will be ready?

**Comment by derekparker** [comment]
@coriolinus this feature is already implemented in the latest release of Delve, however it has been left open as there are still some improvements to be made.

**Comment by coriolinus** [comment]
That's excellent to know, thanks!

**Comment by derekparker** [comment]
Going to officially close this out as we now have this functionality. We will continue adding more improvements and @aarzilli has done a ton already.
