### ISSUE TITLE
Debugging is not working when the project path is too long

### ISSUE THREAD

**Issue by xzzh999** [go-delve/delve#1634]
see ![vs code issue #2602](https://github.com/microsoft/vscode-go/issues/2602)

**Comment by aarzilli** [comment]
Judging by the logs you posted on the other issue it looks like your program is simply terminating before hitting any breakpoint, if that's the case either:

1. you didn't set any breakpoints,
2. VSCode has problem setting the breakpoint you specify
3. the breakpoints you set aren't getting hit

we don't maintain the VSCode extension here, to further figure out what your problem is you should do what @ramya-rao-a said in the other issue, but also pass `--log --log-output=rpc` to dlv.

**Comment by aarzilli** [comment]
Closing, no feedback.
