### ISSUE TITLE
could not launch process: stub exited while waiting for connection

### ISSUE THREAD

**Issue by ccconnor** [go-delve/delve#1650]
1. What version of Delve are you using (`dlv version`)?
```
Delve Debugger
Version: 1.2.0
Build: $Id: 068e2451004e95d0b042e5257e34f0f08ce01466 $
```
2. What version of Go are you using? (`go version`)?
```
go version go1.12.4 darwin/amd64
```
3. What operating system and processor architecture are you using?
```
ProductName:    Mac OS X
ProductVersion: 10.14
BuildVersion:   18A391
Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
```
4. What did you do?
```
go get -u github.com/go-delve/delve/cmd/dlv
dlv exec ./burrow
```
5. What did you expect to see?
```
Type 'help' for list of commands.
(dlv) 
```
6. What did you see instead?
```
could not launch process: stub exited while waiting for connection: exit status 0
```

**Comment by aarzilli** [comment]
If you google the error message you'll find that this problem has been reported several times. It's usually a configuration problem: you either don't have permissions to debug (possibly because you are connecting through ssh), or you have a botched entry in /etc/hosts.

If you can't solve the problem pass `--log --log-output=lldbout,gdbwire` and post the output. Also run `/Library/Developer/CommandLineTools/Library/PrivateFrameworks/LLDB.framework/Versions/A/Resources/debugserver ./burrow` manually and see what happens.

**Comment by ccconnor** [comment]
Sovled. Google didn't help. This is the way.

> If you didn't enable Developer Mode using XCode you will be asked to authorize the debugger every time you use it. To enable Developer Mode and only have to authorize once per session use: 
sudo /usr/sbin/DevToolsSecurity -enable

I thought it would ask me for a password, not a panic, so I omitted it.
Thanks!
