### ISSUE TITLE
Feature: add ability to stop mozilla rr recording

### ISSUE THREAD

**Issue by nd** [go-delve/delve#1747]
At the moment delve waits for `rr record` to finish which happen when the inferior terminates. 
Ability to stop recording without program termination is useful for long running servers which do not exit. [It looks like](https://github.com/mozilla/rr/blob/master/src/RecordCommand.cc#L473) recording can be stopped by sending SIGTERM to rr.

**Comment by aarzilli** [comment]
The problem with doing this is that we start serving the API after we've finished recording everything so there's no way to even receive a request like this at the moment. Implementing this would require changing the rpc2 server code so that it can operate without a debugger object or with a partially initialized one.

**Comment by derekparker** [comment]
Closed via https://github.com/go-delve/delve/pull/1890.
