### ISSUE TITLE
symbol link issue

### ISSUE THREAD

**Issue by epheien** [go-delve/delve#1808]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Version: 1.3.2
2. What version of Go are you using? (`go version`)?
go version go1.12.4 darwin/amd64
3. What operating system and processor architecture are you using?
macOS 10.14.6
4. What did you do?
see below
5. What did you expect to see?
see below
6. What did you see instead?
see below

## Reproduce
```
$ cd tmp
$ ln -s ../a.go
$ realpath a.go
/Users/eph/test/a.go
$ pwd
/Users/eph/test/tmp
$ dlv debug a.go
Type 'help' for list of commands.
(dlv) b /Users/eph/test/a.go:14
Command failed: Location "/Users/eph/test/a.go:14" not found
(dlv) b /Users/eph/test/tmp/a.go:14
Breakpoint 1 set at 0x10f47db for main.main() ./a.go:14
```

pdb3 (Python debugger) can handle this situation

**Comment by derekparker** [comment]
To be honest I'm struggling to see the value of supporting this, or even when this situation would arise. If you want to set a breakpoint using the original directory and source files and not the symlinks you could simply use the substitute-path command once and then you would not run into this issue during your debug session. You can even set it permanently in the config file and never have to think about it again.

The problem with supporting this, even optionally, is it adds complexity that I'm not really sure is worth the benefit, as there's technically already a pretty clean way of accomplishing what you're trying to accomplish. It's not like Delve is having a problem resolving the symlink or finding the actual file that the symlink is pointing to or anything.

If you look at the PR submitted to solve this, there are definite performance issues with solving this problem. Essentially now we have to look at every file and follow every symlink, which becomes a `O(n*m)` problem where `n` is the number of sources listed in debug info and `m` is the number of symlinks for each file. And this issue is compounded if, as mentioned in the PR, the files we are trying to stat are in some sort of network mount point where stat'ing a file could be an expensive operation when done in a tight loop. I'm open to discussion, but just being honest I doubt we will support this use case as it's not worth the complexity.

**Comment by epheien** [comment]
> To be honest I'm struggling to see the value of supporting this, or even when this situation would arise. If you want to set a breakpoint using the original directory and source files and not the symlinks you could simply use the substitute-path command once and then you would not run into this issue during your debug session. You can even set it permanently in the config file and never have to think about it again.
> 
> The problem with supporting this, even optionally, is it adds complexity that I'm not really sure is worth the benefit, as there's technically already a pretty clean way of accomplishing what you're trying to accomplish. It's not like Delve is having a problem resolving the symlink or finding the actual file that the symlink is pointing to or anything.
> 
> If you look at the PR submitted to solve this, there are definite performance issues with solving this problem. Essentially now we have to look at every file and follow every symlink, which becomes a `O(n*m)` problem where `n` is the number of sources listed in debug info and `m` is the number of symlinks for each file. And this issue is compounded if, as mentioned in the PR, the files we are trying to stat are in some sort of network mount point where stat'ing a file could be an expensive operation when done in a tight loop. I'm open to discussion, but just being honest I doubt we will support this use case as it's not worth the complexity.

As I known, pdb3 can support it.
```
tmp $ pdb3 a.py
> /Users/eph/test/tmp/a.py(3)<module>()
-> import os
(Pdb) b /Users/eph/test/a.py:93
Breakpoint 1 at /Users/eph/test/a.py:93
(Pdb) b /Users/eph/test/tmp/a.py:93
Breakpoint 2 at /Users/eph/test/tmp/a.py:93
(Pdb)
```

and some tool (like vim) only report the real path
```
~ $ ls -l neovim
lrwxr-xr-x 1 eph staff 10  1 28 12:28 neovim -> wsp/neovim
~ $ cd neovim
~ $ pwd
/Users/eph/neovim
~ $ # run vim and run ':pwd' in vim, it report '/User/eph/wsp/neovim'
```
I loss `~/neovim` info, so I can not set breakpoint via abspath of file

**Comment by derekparker** [comment]
Python does not encode debug information as it's running through an interpreter, so it looks for files directly on the filesystem and not in some debug information that is encoded into the process being run. When Go encodes the information of which source files were used to compile the final binary it does not resolve symlinks, so if you compiled your binary in a symlink'd directory, that's what will show up in the debug information.

FWIW (not that I feel we should copy all these semantics) GDB exhibits the same behavior of Delve. I'm sorry to say I'm going to close this issue as WONTFIX. If you want to use the path your symlink resolves to, simply use the config directive `config substitute-path <symlink-dir> <original-dir>`.
