### ISSUE TITLE
service/dap: leaves the temporary binary behind

### ISSUE THREAD

**Issue by hyangah** [go-delve/delve#2411]
This is caused by race during Disconnect request handling.

1. Disconnect request is received, and [`onDisconnectRequest`](https://github.com/go-delve/delve/blob/b120b11cc383554064e3e2da36d29e4c5299a988/service/dap/server.go#L636-L659) starts the disconnect sequence, including detaching from the debugee.
2. `s.signalDisconnect` is called at the end.
3. `s.signalDisconnect` closes [`s.config.DisconnectChan`](https://github.com/go-delve/delve/blob/b120b11cc383554064e3e2da36d29e4c5299a988/service/dap/server.go#L189) before deleting the temporary  binary.
4. Closing of `s.config.DisconnectChan` unblocks [`waitForDisconnectSignal`](https://github.com/go-delve/delve/blob/b120b11cc383554064e3e2da36d29e4c5299a988/cmd/dlv/cmds/commands.go#L455).
5. [`server.Stop`](https://github.com/go-delve/delve/blob/b120b11cc383554064e3e2da36d29e4c5299a988/cmd/dlv/cmds/commands.go#L452) +[`os.Exit`](https://github.com/go-delve/delve/blob/b120b11cc383554064e3e2da36d29e4c5299a988/cmd/dlv/cmds/commands.go#L458) races with the remaining of `s.signalDisconnect`.

If `os.Exit` runs first, the temporary binary deletion by `s.signalDisconnect` won't complete. 

cc @polinasok @suzmue @aarzilli

**Comment by polinasok** [comment]
Thank you for tracking this. We could delete the binary first or move this logic to Stop().

**Comment by polinasok** [comment]
@aarzilli Would there be an issue with deleting a binary file before running Debugger.Detach as part of teardown?

**Comment by aarzilli** [comment]
Does that work on windows?

**Comment by polinasok** [comment]
> Does that work on windows?

Unfortunately I don't have a windows machine to confirm this. I was just reworking this code and realized that the current version of dlv-dap code might trigger binary deletion before calling Detach via Stop() in cases where the disconnectChan is triggered due to a client connection error as opposed to an explicit Detach request. So the binary might be in use when we delete. That could be a source of some of the "access denied" errors on Windows (but not all because in other cases we do detach before deleting and still have it with both dap and rpc), but maybe can also cause debugger errors because the backend needs to reference the source file while processing some pending request, but no longer can. I am just imagining this - I haven't actually observed that happen. Earlier I suggested deleting he binary before closing disconnectChan to fix the race, but now I think that was not a good idea. I will send out a PR that does this in Stop().

**Comment by aarzilli** [comment]
> but maybe can also cause debugger errors because the backend needs to reference the source file while processing some pending request, but no longer can

The BinaryInfo object does keep the executable file open and reads from it through the *dwarf.Data object.
