### ISSUE TITLE
DLV debugger assigns incorrect value as error (unreadable invalid interface type: key not found)

### ISSUE THREAD

**Issue by jsgoupil** [go-delve/delve#2593]
1. What version of Delve are you using (`dlv version`)?
Version: 1.6.1
Build: $Id: 114218c22f3791287c4bc2f4ff35a846a1416ee9 $

2. What version of Go are you using? (`go version`)?
go version go1.16.5 windows/amd64

3. What operating system and processor architecture are you using?
Windows 10 x64

4. What did you do?
A simple call that return error = nil

5. What did you expect to see?
error being nil

6. What did you see instead?
it is not nil and propagates as non-nil further when debugging
The error is
`(unreadable invalid interface type: key not found)`
The debugger becomes a bit "unstable", I don't fully understand why it jumps between multiple "return" from the caller. But 2 caller above the stack, it "recovers" as err == nil.

Using Visual Studio Code 1.58. I had problems with proc.go always opening, so I followed a recommendation and installed dlv for debugging and set this in my settings.
```
    "go.delveConfig": {
        "debugAdapter": "dlv-dap",
    }
```
This shows the error being non-nil
![image](https://user-images.githubusercontent.com/808649/125831788-26cd8b9d-2cd5-4ff5-a848-4d5a7db8d111.png)

If I set the error with `var a error` instead of declaration assignation operator, it works.
![image](https://user-images.githubusercontent.com/808649/125831902-454ae020-da09-433d-b00a-8bb67b62b677.png)

This is using the old "legacy" debugger without the settings "debugAdapter". It works fine.
![image](https://user-images.githubusercontent.com/808649/125832005-39b22251-f76e-4984-8551-99692520ef9e.png)

**Comment by polinasok** [comment]
You are likely using two different versions of dlv, stable with legacy adapter and a more recent dlv-dap.
You could try using both versions of with the terminal client to see if anything changed in the dlv backend vs being an issue is in the adapter layer. `dlv debug program` vs `dlv-dap debug program`.

My guess would be that dlv behaves the same way in both cases, and the difference is in how we print out the values.

In case of dlv-dap, we use a function in the dlv repo that first checks for unreadable memory (e.g. because it is uninitialized), then dispatches pretty printing by type.
https://github.com/go-delve/delve/blob/9df8f1499f10432698ea184c839a2a6f75264e93/service/api/prettyprint.go#L42-L45
In case of legacy adapter, a function is written in TypeScript with very similar structure as the internal dlv code, but it is missing the unreadable check. So instead it dives into the special case for escaped interfaces.
https://github.com/golang/vscode-go/blob/03a831540a1fca9029b43541b3699c44c456d692/src/debugAdapter/goDebug.ts#L2385-L2393
That logic was copied from here in dlv, but is never reached in dlv-dap case.
https://github.com/go-delve/delve/blob/9df8f1499f10432698ea184c839a2a6f75264e93/service/api/prettyprint.go#L93-L98

That is why you see untyped "nil" and not typed "nil <error>" like with ~r3. Untyped "nil" looks less scary than "unreadable", but both point to something being not quite in-scope/initialized. 

That said I do not understand why you still see that value on the next line after the variable was declared. This is what I see. But I have an older version of Go. And I am on MacOS. 

For example using dlv cli:
```
(dlv) b issue2593
Breakpoint 1 (enabled) set at 0x10c4e00 for main.issue2593() ./temp.go:41
(dlv) c
> main.issue2593() ./temp.go:41 (hits goroutine(1):1 total:1) (PC: 0x10c4e00)
    40:
=>  41: func issue2593() error {
    42:         var a error
    43:         b := a
    44:         return b
    45: }
    46:
(dlv) locals
(no locals)
(dlv) args
~r0 = error (unknown invalid)
(dlv) n
> main.issue2593() ./temp.go:42 (PC: 0x10c4e16)
    40:
    41: func issue2593() error {
=>  42:         var a error
    43:         b := a
    44:         return b
    45: }
    46:
(dlv) locals
a = (unreadable invalid interface type: could not find str field)
(dlv) args
~r0 = error nil
(dlv) n
> main.issue2593() ./temp.go:43 (PC: 0x10c4e1e)
    40:
    41: func issue2593() error {
    42:         var a error
=>  43:         b := a
    44:         return b
    45: }
    46:
(dlv) locals
a = error nil
b = (unreadable invalid interface type: could not find str field)
(dlv) n
> main.issue2593() ./temp.go:44 (PC: 0x10c4e25)
    40:
    41: func issue2593() error {
    42:         var a error
    43:         b := a
=>  44:         return b
    45: }
    46:
(dlv) locals
a = error nil
b = error nil
(dlv) 
```

**Comment by polinasok** [comment]
> The debugger becomes a bit "unstable", I don't fully understand why it jumps between multiple "return" from the caller.  But 2 caller above the stack, it "recovers" as err == nil.

Could you please elaborate more on this?

**Comment by jsgoupil** [comment]
I appreciate the message here. I think I was able to get a smaller repro. It might not be delve the problem here.
I'm brand new to Go and maybe it's just a positioning of the debug line that is incorrect. The positioning of the debug line is the same for the legacy or dlv.

![image](https://user-images.githubusercontent.com/808649/125875257-e172ca9f-1f01-48f1-b88c-39125dafa2a1.png)

But with dlv, the error message is not the same and "confusing".

In the end, I would have expected to not go inside the "if"

```
func issue2593(z interface{}) error {

	switch t := z.(type) {
	case string:
		if err := issue2593_call(); err != nil {
			// Will go here.
			return err
		}
	default:
		fmt.Print(t)
	}

	// Then here
	return nil
}

func issue2593_call() error {
	return nil
}

func main() {
	err := issue2593("test")
	// Will print <nil>
	fmt.Print(err)
}
```

Maybe the breakpoint is supposed to stop on the `err != nil` ?

**Comment by jsgoupil** [comment]
With another call, that looks even more confusing:

![image](https://user-images.githubusercontent.com/808649/125877316-182d6c9e-09ef-4efe-9750-5149d70df1c1.png)

**Comment by polinasok** [comment]
Thank you so much for the test case. I am able to reproduce what you are seeing both with vscode and with dlv cli while stepping through the code. And I agree that it looks off. 

Legacy
![image](https://user-images.githubusercontent.com/51177946/125894437-1cd9d03c-1a7e-436a-87ed-10b1baafc123.png)
Dlv-dap
![image](https://user-images.githubusercontent.com/51177946/125894635-501cdfd5-ad63-478d-9cb0-2b2acbf2892f.png)

There are two issues here:
1) printing "nil" (untyped) vs "unreadable"
2) visually entering if (including having err displayed as in-scope with nil/unreadable value), but not actually executing that code

Investigating.
I have upgraded my Go version. Here is what I used:
```
polina-macbookair2:delve polina$ go version
go version go1.16.6 darwin/amd64
polina-macbookair2:delve polina$ dlv version
Delve Debugger
Version: 1.6.1
Build: $Id: 114218c22f3791287c4bc2f4ff35a846a1416ee9 $
polina-macbookair2:delve polina$ ./dlv version
Delve Debugger
Version: 1.6.1
Build: 3bd088978f6d8248959e16574396fdc0cc346f13
```

**Comment by polinasok** [comment]
With `--log-output=rcp`
```
    45:				// Will go here.
=>  46:				return err
    47:			}
    48:		default:
    49:			fmt.Println(t)
    50:		}
    51:		// Then here
(dlv) p err
2021-07-15T22:38:39-07:00 debug layer=rpc <- RPCServer.Eval(rpc2.EvalIn{"Scope":{"GoroutineID":-1,"Frame":0,"DeferredCall":0},"Expr":"err","Cfg":{"FollowPointers":true,"MaxVariableRecurse":1,"MaxStringLen":64,"MaxArrayValues":64,"MaxStructFields":-1}})
2021-07-15T22:38:39-07:00 debug layer=rpc -> *rpc2.EvalOut{"Variable":{"name":"err","addr":824634400160,"onlyAddr":false,"type":"error","realType":"error","flags":0,"kind":20,"value":"","len":0,"cap":0,"children":[],"base":0,"unreadable":"invalid interface type: could not find str field","LocationExpr":"[block] DW_OP_fbreg -0x68 ","DeclLine":44}} error: ""
(unreadable invalid interface type: could not find str field)
```
And same logging from legacy adapter, where you can see that inspite of different pretty printing the underlying is the same

![image](https://user-images.githubusercontent.com/51177946/125898179-1d1eac50-3238-49cd-93b8-0b9691b51596.png)

**Comment by polinasok** [comment]
This looks like some kind of debugging line info bug. I played with the code a bit to reduce inlining. This version also visually enters 'if err != nill' AND reports 'err: error nil', but doesn't actually execute that statement (as it should).

![image](https://user-images.githubusercontent.com/51177946/125990975-aefee517-3008-4452-839e-7948191e8619.png)

This version with the function call commented out says there is no code on the line where 'return err' is.
![image](https://user-images.githubusercontent.com/51177946/125990892-ab908e67-1e21-40d0-819f-34d57a663d5b.png)

Extra logging
```
(dlv) b temp.go:48
2021-07-16T11:14:25-07:00 debug layer=rpc <- RPCServer.FindLocation(rpc2.FindLocationIn{"Scope":{"GoroutineID":-1,"Frame":0,"DeferredCall":0},"Loc":"temp.go:48","IncludeNonExecutableLines":false,"SubstitutePathRules":[]})
2021-07-16T11:14:25-07:00 debug layer=rpc -> *rpc2.FindLocationOut{"Locations":null} error: "could not find statement at /Users/polina/go/src/temp.go:48, please use a line with a statement"
Command failed: could not find statement at /Users/polina/go/src/temp.go:48, please use a line with a statement
```
```
(dlv) b temp.go:48
2310 +3.531804 sec [0397/2603]: ::read ( 5, 0x7000097e1b00, 1024 ) => 8 err = 0x00000000
2311 +0.000028 sec [0397/2603]: read: $m8,8#09
2312 +0.000011 sec [0397/2603]: getpkt: $m8,8#09
2313 +0.000086 sec [0397/0103]: RNBRunLoopInferiorExecuting ctx.Events().WaitForSetEvents(0x000000a5) => 0x00000020 (read_packet_available )
2314 +0.000021 sec [0397/0103]: HandleReceivedPacket ("m8,8");
2315 +0.000033 sec [0397/0103]: error: ::mach_vm_read ( task = 0x1807, addr = 0x00000008, size = 8, data => 0x00000000, dataCnt => 0 ) err = (os/kern) invalid address (0x00000001)
2316 +0.000011 sec [0397/0103]: MachTask::ReadMemory ( addr = 0x00000008, size = 8, buf = 0x7ffeeb4fdb71) => 0 bytes read
2317 +0.000011 sec [0397/0103]:  3532040 RNBRemote::SendPacket (E08) called
2318 +0.000028 sec [0397/0103]: ::write ( socket = 5, buffer = 0x7ffeeb4fd9d9, length = 7) => 7 err = 0x00000000
2319 +0.000010 sec [0397/0103]: putpkt: $E08#00
2320 +0.000007 sec [0397/0103]: sent: $E08#00
2321 +0.000009 sec [0397/0103]: RNBRunLoopInferiorExecuting ctx.Events().WaitForSetEvents(0x000000a5) ...
2322 +0.000162 sec [0397/2603]: ::read ( 5, 0x7000097e1b00, 1024 ) => 8 err = 0x00000000
2323 +0.000015 sec [0397/2603]: read: $m0,8#01
2324 +0.000008 sec [0397/2603]: getpkt: $m0,8#01
2325 +0.000068 sec [0397/0103]: RNBRunLoopInferiorExecuting ctx.Events().WaitForSetEvents(0x000000a5) => 0x00000020 (read_packet_available )
2326 +0.000019 sec [0397/0103]: HandleReceivedPacket ("m0,8");
2327 +0.000033 sec [0397/0103]: error: ::mach_vm_read ( task = 0x1807, addr = 0x00000000, size = 8, data => 0x00000000, dataCnt => 0 ) err = (os/kern) invalid address (0x00000001)
2328 +0.000011 sec [0397/0103]: MachTask::ReadMemory ( addr = 0x00000000, size = 8, buf = 0x7ffeeb4fdb71) => 0 bytes read
2329 +0.000010 sec [0397/0103]:      380 RNBRemote::SendPacket (E08) called
2330 +0.000057 sec [0397/0103]: ::write ( socket = 5, buffer = 0x7ffeeb4fd9d9, length = 7) => 7 err = 0x00000000
2331 +0.000012 sec [0397/0103]: putpkt: $E08#00
2332 +0.000008 sec [0397/0103]: sent: $E08#00
2333 +0.000008 sec [0397/0103]: RNBRunLoopInferiorExecuting ctx.Events().WaitForSetEvents(0x000000a5) ...
Command failed: could not find statement at /Users/polina/go/src/temp.go:48, please use a line with a statement
```

I am out of my depth at this point as we are well past the variable pretty printing from DAP adapter.
@aarzilli @derekparker 

I also want to point out that you should not see unreadable interface values routinely when debugging. In my experience, they either show up because of how variable declaration line is determined, which used to make the variable in-scope before it was properly initialized. This was demonstrated above with an older Go version. But it has been removed since then for non-arg variables (see https://github.com/go-delve/delve/pull/2011/commits/225c8bfb749aba598c8661eedf1d0f303f23ae53). Or this indicates some problem, like in your case. And in that case, I think it is better if they look more obvious and not hidden with innocent looking `nil`.

**Comment by derekparker** [comment]
I've spent a bit of time digging into this just now.

The arrow shows where we are stopped in the assembly code.

```
        main.go:8       0x4b6a80        488b4008                        mov rax, qword ptr [rax+0x8]
        main.go:8       0x4b6a84        48894c2450                      mov qword ptr [rsp+0x50], rcx
        main.go:8       0x4b6a89        4889442458                      mov qword ptr [rsp+0x58], rax
        main.go:9       0x4b6a8e        e80d010000                      call $main.issue2593_call
=>    main.go:9       0x4b6a93        488b442408                      mov rax, qword ptr [rsp+0x8]
        main.go:11      0x4b6a98        488b0c24                        mov rcx, qword ptr [rsp]
        main.go:9       0x4b6a9c        48833c2400                      cmp qword ptr [rsp], 0x0
        main.go:9       0x4b6aa1        48894c2460                      mov qword ptr [rsp+0x60], rcx
        main.go:9       0x4b6aa6        4889442468                      mov qword ptr [rsp+0x68], rax
        main.go:9       0x4b6aab        7502                            jnz 0x4b6aaf
        main.go:9       0x4b6aad        eb20                            jmp 0x4b6acf
        main.go:11      0x4b6aaf        48898c24c8000000                mov qword ptr [rsp+0xc8], rcx
```

As you can see we have the `call` followed by 2 `mov` instructions (for the error interface which is 2 words) followed by the `cmp` instruction we would expect. It's very odd that the compiler generates that line number for the 2nd `mov` instruction. However, while the compiler does seem to be emitting incorrect line number information in this case, this may still be Delve's fault. 

Given the line number information present in the binary:

```
  [0x0002b50c]  Special opcode 225: advance Address by 22 to 0x4b6a8e and Line by 1 to 9
  [0x0002b50d]  Set is_stmt to 0
  [0x0002b50e]  Special opcode 54: advance Address by 5 to 0x4b6a93 and Line by 0 to 9
  [0x0002b50f]  Set is_stmt to 1
  [0x0002b510]  Special opcode 56: advance Address by 5 to 0x4b6a98 and Line by 2 to 11
  [0x0002b511]  Set is_stmt to 0
  [0x0002b512]  Special opcode 42: advance Address by 4 to 0x4b6a9c and Line by -2 to 9
  [0x0002b513]  Set is_stmt to 1
  [0x0002b514]  Special opcode 196: advance Address by 19 to 0x4b6aaf and Line by 2 to 11
  [0x0002b515]  Set is_stmt to 0
  [0x0002b516]  Special opcode 84: advance Address by 8 to 0x4b6ab7 and Line by 0 to 11
  [0x0002b517]  Set is_stmt to 1
```

When you are `next`ing and suddenly go to line 11 when you wouldn't expect it's because of this line number information. However, Delve really shouldn't be trying to stop at that address because the line number program has explicitly set `is_stmt` to 0 so Delve shouldn't be setting a `next` breakpoint there. I'll keep digging.

**Comment by polinasok** [comment]
I got some expert help on my end and we found the same thing with he mov instruction with he wrong line. I am about to file a bug against the Go compiler.

**Comment by derekparker** [comment]
> I got some expert help from @heschi, and we found the same thing with he mov instruction with the wrong line. I am about to file a bug against the Go compiler.

Great, I was going to ping @heschi or @aclements about filing a bug against the compiler, so thank you!

However, this does also seem to be a bug in Delve in that for `next` breakpoints we set we were not respecting the `is_stmt` register in the line number program. I've sent in a PR to fix that which does indeed fix this issue.

**Comment by polinasok** [comment]
@derekparker Does your fix also fix the modified program where a line was not found even though it existed?

**Comment by polinasok** [comment]
```
func issue2593(z interface{}) error {
	switch t := z.(type) {
	case string:
		var err error
		//err = issue2593_nil()
		if err != nil {
			// Will go here.
			return err // <<<<<<<< line not fouond
		}
	default:
		fmt.Println(t)
	}
	// Then here
```

**Comment by polinasok** [comment]
Oh, and what about setting a breakpoint at line 11 in the original code and hitting it with continue without using next, which is also incorrect?

**Comment by derekparker** [comment]
> @derekparker Does your fix also fix the modified program where a line was not found even though it existed?

No it does not seem to. I can look into that as well.

**Comment by derekparker** [comment]
> Oh, and what about setting a breakpoint at line 11 in the original code and hitting it with continue without using next, which is also incorrect?

Can you please open a new issue on our tracker for this? I'll investigate more next week.

**Comment by polinasok** [comment]
The good news is that the most recent Go release candidate doesn't seem to have this line issue. Hopefully it was a deliberate fix and not some masking side effect in select cases.

**Comment by polinasok** [comment]
@derekparker So we understand why we hit line 11 in the middle of processing instructions that resulted from the function call on line 9. And until the function call instructions are fully executed, we are still at the declaration line, so the value of `err` is not fully initialized. Normally we would not see it at all, but because 11>9, it showed up as in-scope. So I guess there is nothing for dlv backend or dap value printer here to do, is there?

**Comment by aarzilli** [comment]
It seems that the compiler conflates the assignment to `err` from the function call return value  with the `return err` statement that follows it, there's nothing we can do about this.
