### ISSUE TITLE
service/dap: TestNextParked flaky

### ISSUE THREAD

**Issue by aarzilli** [go-delve/delve#2762]
https://delve.teamcity.com/viewLog.html?buildId=27717

**Comment by polinasok** [comment]
@aarzilli In the failure log the process runs to completion, but exits with status -1 instead of 0. Would could be causing flakiness in the termination status of [parallel_next.go](https://github.com/go-delve/delve/blob/master/_fixtures/parallel_next.go)? Is that expected under certain conditions or a bug somewhere? Would skipping the status check to unflake the test just paper over a problem that should be investigated?

**Comment by aarzilli** [comment]
My guess is https://github.com/go-delve/delve/blob/9013a121d8bc6359018bccfaa1f256a8870d01c7/pkg/proc/native/proc_linux.go#L442, we get some stop reason, try to resume the main thread and find that it's gone. I don't know why that happens but I think it does sometimes, In those cases we don't have the exit status.
It could also be that the target process got a SIGHUP, but I don't see why that would be the case.

**Comment by polinasok** [comment]
Hmm, it thinks it hasn't exited?
https://github.com/go-delve/delve/blob/9013a121d8bc6359018bccfaa1f256a8870d01c7/vendor/golang.org/x/sys/unix/syscall_linux.go#L320-L325
We get this status when we get debugger state after the command that returned exited status. We have a TODO to refactor that code. Would that help?

**Comment by aarzilli** [comment]
>  We get this status when we get debugger state after the command that returned exited status. We have a TODO to refactor that code. Would that help?

I think this all happens inside ContinueOnce.
