### ISSUE TITLE
int and int64 fields in JSON API

### ISSUE THREAD

**Issue by kostya-sh** [go-delve/delve#280]
API types from service/api/types.go have many int, int64 and uint64 fields that are represented as numbers in JSON.

However not all languages support int64 types. In particular Javascript has only IEEE-754 8-byte float type that can only represent 53-bit integers without loss of precision.

I suggest to serialize all numbers as strings. E.g.:

```
ID int `json:"id,string"`
```

**Comment by aarzilli** [comment]
Because of address space restrictions on supported hardware real addresses never have more than 53bits. With the advent of regabi in go1.17 we actually started returning addresses with more than 53bits to give unique addresses to registerized variables. Nobody complained about this issue, so I guess it doesn't matter.
