### ISSUE TITLE
Display format for time.Time

### ISSUE THREAD

**Issue by alialtun14** [go-delve/delve#2841]
The value of time.Time is displayed as follows. 

    time.Time {wall: 0, ext: 63775987200, loc: *time.Location nil}

Can it convert the display format to a readable one?

**Comment by polinasok** [comment]
```
(dlv) call mytime.String()
> main.main() ./main.go:11 (PC: 0x10abdde)
Values returned:
	~r0: "2021-12-28 17:22:14.903126 -0800 PST m=+3.522804008"
```

```
(dlv) call mytime.Format("2006-01-02 15:04:05")
> main.main() ./main.go:11 (PC: 0x10abdde)
Values returned:
	~r1: "2021-12-28 17:22:14"
```
```
(dlv) call time.Now().String()
> main.main() ./main.go:11 (PC: 0x10abdde)
Values returned:
	~r0: "2021-12-28 17:26:48.564652 -0800 PST m=+277.178154193"
```

**Comment by polinasok** [comment]
If you are using VS Code UI, you can [file an issue against vscode-go](https://github.com/golang/vscode-go/issues) to have a human-readable representation of the time added as a "child". We have recently added a similar feature for bytes - see [here](https://github.com/golang/vscode-go/issues/1459#issuecomment-868792083). Otherwise, your options are `call` commands in the DEBUG CONSOLE or WATCH.

**Comment by alialtun14** [comment]
Thank you for your interest. I have filed an [issue](https://github.com/golang/vscode-go/issues/1980#issue-1090224784) against vscode-go.
