### ISSUE TITLE
failed to load golang source code from relative path when debugging bazel

### ISSUE THREAD

**Issue by MohitNagpaldce** [go-delve/delve#2994]
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? -  1.8.2
2. What version of Go are you using? (`go version`)? go version go1.17.8 darwin/arm64 
3. What operating system and processor architecture are you using? macOS Monterey, Apple M1 Pro.
4. What did you do? - Run app with bazel and do dlv connect to headless dlv from different window and added breakpoint.
5. What did you expect to see? Breakpoint hits but source code does not come up. 
6. What did you see instead? Assembly code comes up instead of actual code. 

Run the app with bazel run.
A) bazel run --compilation_mode=dbg --run_under='dlv exec --headless
' //src/pathtoapp/app:app

B) Added substitute path in dlv config file 
-substitute-path in dlv config ( $HOME/.dlv/config.yml)

-substitute-path: 
-{from: /private/var/tmp/_bazel_mohitn/d3eb9a0ef06857aebc54b41ff425d2ee/execroot/__main__/bazel-out/darwin_arm64-dbg/bin/src, 
to: /Users/mohitn/go-code/src}

C) dlv connect 127.0.0.1:63412 from different window. 
 once breakpoint hits , it still shows the assembly code not the source code files.

**Comment by aarzilli** [comment]
Post the output you get with `--log --log-output=rpc`.

**Comment by MohitNagpaldce** [comment]
Does not give any additional logs:

![image](https://user-images.githubusercontent.com/11233980/166390613-78271254-afe9-4df3-90ff-e0dd8bf08f90.png)

**Comment by aarzilli** [comment]
Those options need to be passed to the backend not to the `connect` command. It's hard to say what the problem would be from your screenshot since it's so heavily edited, but I would guess that the executable has been partially stripped of debug information. There's an entry for the function you are setting a breakpoint on but debug_line, for some reason, doesn't cover it.

**Comment by MohitNagpaldce** [comment]
I think something is missing in substitute path. bazel is launching like this: Got a connection, launched process 

/private/var/tmp/_bazel_mohitn/d3eb9a0ef06857aebc54b41ff425d2ee/execroot/__main__/bazel-out/darwin_arm64-dbg/bin/src/xxx/xxxx/xxx/app/app_/app 

and substitute path from config is : 
-{from: /private/var/tmp/_bazel_mohitn/d3eb9a0ef06857aebc54b41ff425d2ee/execroot/main/bazel-out/darwin_arm64-dbg/bin/src,
to: /Users/mohitn/go-code/src}

is this right combination ?

**Comment by aarzilli** [comment]
I don't think this has anything to do with substitute path, but I can't tell for sure because all the information I have about this are edited screenshots.

**Comment by chancila** [comment]
I am having issues with something similar as well...debugging works fine if I initiate debugging in the directory where the relative sources are, however if I run the executable somewhere else the debugger cannot find the source files.

can there be more specific documentation on how substitute-path is intended to be used? How does it match the source path in the debug info? What is the valid syntax? If a path is `a/b/c.go` do I need to specify the whole path or a prefix? Would from: "./a/b/c.go" match that path or its wrong because it starts with a `./`? This syntax is okay in lldb and gdb.

In lldb or gcd you can re-root relative paths with something like `settings set target.source-map . /new/path`. ie mapping `"." -> "/new/path"`

example invocation:

```
dlv exec ~/bin/bzl_dev query //...                                                                                                                                                                        

Type 'help' for list of commands.
(dlv) config substitute-path . /Users/chancila/Snapchat/Dev/bzl <--- intention is to re-root all relative sources to this dir
(dlv)
(dlv) b render_proc.go:159
Breakpoint 1 set at 0x1054f5ae4 for github.sc-corp.net/Snapchat/bzl/src/go/lib/ui.(*renderProcDefault).processEvents() src/go/lib/ui/render_proc.go:159
(dlv) c
> github.sc-corp.net/Snapchat/bzl/src/go/lib/ui.(*renderProcDefault).processEvents() src/go/lib/ui/render_proc.go:159 (hits goroutine(22):1 total:1) (PC: 0x1054f5ae4)
(dlv) l
> github.sc-corp.net/Snapchat/bzl/src/go/lib/ui.(*renderProcDefault).processEvents() src/go/lib/ui/render_proc.go:159 (hits goroutine(22):1 total:1) (PC: 0x1054f5ae4)
Command failed: open src/go/lib/ui/render_proc.go: no such file or directory
(dlv) ^C
(dlv) exit
```

I have also tried setting mappings `src /Users/chancila/Snapchat/Dev/bzl/src` but that didn't work either.

**Comment by aarzilli** [comment]
> can there be more specific documentation on how substitute-path is intended to be used? How does it match the source path in the debug info?

https://github.com/go-delve/delve/blob/ff3370e67647fe1109481ef4c005b1f8a20c25ee/pkg/locspec/locations.go#L482 it just uses strings.HasSuffix

**Comment by aarzilli** [comment]
Closing, likely user error. Also, see FAQ.
