### ISSUE TITLE
Minimum Go version has changed to 1.21?

### ISSUE THREAD

**Issue by jamietanna** [go-delve/delve#3588]
As noted [on Mastodon](https://mastodon.social/@cks/111484989725312650) when running with Go 1.21, Go will not allow building with `-mod=readonly`, and will insist you use `go mod tidy`. 

As per a [follow up comment](https://www.jvt.me/mf2/2023/11/1asep/) this appears to be due to one of our dependencies, `github.com/goretk/gore`, expecting a minimum of Go 1.21.

**Comment by prattmic** [comment]
Note that this is a limitation of `go build -mod=vendor` (the default since delve has a vendor directory). The build should fail, but `go build -mod=vendor` is failing to detect the problem.

In fact, the Go tool shouldn’t have even allowed creation of that incompatible vendor tree in the first place, but I think if the vendoring was done with an old version of Go it could happen.

**Comment by jamietanna** [comment]
Is it also worth getting CI to run this? / having CI build against multiple Go versions to flag issues with different Go versions in the future?

**Comment by aarzilli** [comment]
We're already testing multiple versions of go in CI, I don't know why this isn't detected there (maybe because we don't specify -mod=readonly and it defaults to -mod=vendor because of the vendor directory).
